### ISSUE TITLE
can you help me to use this repo

### ISSUE THREAD

**Issue by prat23k** [saul/dvsa-auto-booker#1]
thank you for such a helpful repo,i did below steps received below errors if i am wrong correct me

Installed ruby in c drive
cloned repo to c drive
installed phantomjs and add to path 
bundle install
created dotenv.env file with required details

C:>cd C:\dvsa-auto-booker-master

C:\dvsa-auto-booker-master>gem install bundler
Fetching: bundler-1.12.5.gem (100%)
Successfully installed bundler-1.12.5
Parsing documentation for bundler-1.12.5
Installing ri documentation for bundler-1.12.5
Done installing documentation for bundler after 7 seconds
1 gem installed

C:\dvsa-auto-booker-master>bundle install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Installing rake 11.1.2
Installing addressable 2.4.0
Installing mime-types-data 3.2016.0221
Installing mini_portile2 2.0.0
Installing rack 1.6.4
Installing ffi 1.9.10
Installing chronic 0.10.2
Installing cliver 0.3.2
Installing dotenv 2.1.1
Installing multi_json 1.12.0
Installing websocket-extensions 0.1.2
Installing rubyzip 1.2.0
Installing websocket 1.2.3
Using bundler 1.12.5
Installing mime-types 3.0
Installing nokogiri 1.6.7.2

Gem::InstallError: nokogiri requires Ruby version < 2.3, >= 1.9.2.
Installing rack-test 0.6.3
Installing childprocess 0.5.9
Installing whenever 0.9.4
Installing websocket-driver 0.6.3 with native extensions

Gem::InstallError: The 'websocket-driver' native gem requires installed build to
ols.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'
An error occurred while installing nokogiri (1.6.7.2), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.7.2'` succeeds before bundling.

C:\dvsa-auto-booker-master>rake auto_book
rake aborted!
LoadError: cannot load such file -- capybara/dsl
C:/dvsa-auto-booker-master/booking_driver.rb:1:in `<top (required)>'
C:/dvsa-auto-booker-master/auto_book.rb:4:in`require_relative'
C:/dvsa-auto-booker-master/auto_book.rb:4:in `<top (required)>'
C:/dvsa-auto-booker-master/Rakefile:2:in`require_relative'
C:/dvsa-auto-booker-master/Rakefile:2:in `block in <top (required)>'
Tasks: TOP => auto_book
(See full trace by running task with --trace)

**Comment by saul** [comment]
`bundle install` failed -- so your best bet is to follow the instructions that it gave:

> Please update your PATH to include build tools or download the DevKit from 'http://rubyinstaller.org/downloads' and follow the instructions at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

Then try `bundle install` again
